import { useSession } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  const { status } = useSession({
    required: true,
  });

  return (
    <>
      <Head>
        <title>DataQuestion</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        DataQuestion
      </main>
    </>
  );
}
